server:
  tomcat:
    uri-encoding: UTF-8
  port: 80


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhs-blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: zhs
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

   #redis的配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-wait: -1
      max-idle: 8
      min-idle: 0
      max-active: 8
#sql日志打印
logging:
  level:
   com.zhs.dao: debug